
--	회사 
CREATE TABLE COMPANY(
	ID			VARCHAR2(10),	-- 회사 ID
	NAME		NVARCHAR2(30),	-- 회사명
	TEL			VARCHAR2(20),	-- 대표전화
	FAX			VARCHAR2(20),	-- FAX
	ADDR		NVARCHAR2(150),	-- 주소
	SALE_EMAIL	VARCHAR2(30),	-- 영업 대표 이메일
	ENG_EMAIL	VARCHAR2(30),	-- 기술 대표 이메일
	INDATE		DATE,			-- 설립일
	OUTDATE		DATE,			-- 폐업일
	STATUS		NUMBER(1, 0)	DEFAULT 0,	-- 0 : 정상운영, 1 : 폐업상태
	CONSTRAINT PK_COMPANY	PRIMARY KEY (ID)
);

-- 회사 연혁
CREATE TABLE COM_HISTORY(
	COM_ID		VARCHAR2(10),	-- 회사 ID
	ID			VARCHAR2(10),	-- 연혁 ID
	STARTDATE	DATE,			-- 시작일
	ENDDATE		DATE,			-- 종료일
	TITLE		NVARCHAR2(150),	-- 제목
	CONTENT		CLOB,			-- 상세 내용
	STATUS		NUMBER(1, 0)	DEFAULT 0,	-- 0 : 정상, 1 : 미사용
	CONSTRAINT	PK_COM_HISTORY	PRIMARY KEY (ID),
	CONSTRAINT	FK_COM_HISTORY_COMPANY	FOREIGN KEY (COM_ID) REFERENCES COMPANY(ID)
);

-- 회사 CI
CREATE TABLE COM_CI(
	COM_ID		VARCHAR2(10),	-- 회사 ID
	ID			VARCHAR2(10),	-- CI ID
	INDATE		DATE,			-- 생성일
	OUTDATE		DATE,			-- 종료일
	FILENAME	NVARCHAR2(200),	-- 파일경로
	BFILE		BLOB,			-- 파일
	STATUS		NUMBER(1, 0)	DEFAULT 0,	-- 0 : 사용, 1 : 미사용
	CONSTRAINT	PK_COM_CI	PRIMARY KEY (ID),
	CONSTRAINT	FK_COM_CI_COMPANY	FOREIGN KEY (COM_ID) REFERENCES COMPANY(ID)
);

CREATE TABLE COM_MEMBER(
	COM_ID		VARCHAR2(10),	-- 회사 ID
	ID			VARCHAR2(30),	-- 직원 ID
	PWD			VARCHAR2(100),	-- PASSWORD
	NAME		NVARCHAR2(30),	-- 이름
	TEL			VARCHAR2(20),	-- 전화
	ROLL		NUMBER(2, 0)	DEFAULT 0,	-- 0 : 고객과 동일메뉴, 1 : 상품 등록 및 관리, 2 : 기타 내용 등록 및 관리, 4 : 매출현황 조회
	INDATE		DATE			DEFAULT SYSDATE,	-- 가입일
	OUTDATE		DATE,								-- 탈퇴일
	STATUS		NUMBER(1, 0)	DEFAULT 0,			-- 0 : 정상, 1 : 탈퇴
	CONSTRAINT	PK_COM_MEMBER PRIMARY KEY (ID),
	CONSTRAINT	FK_COM_MEMBER_COMPANY FOREIGN KEY (COM_ID) REFERENCES COMPANY (COM_ID)
);

-- 제품
CREATE TABLE PRODUCT(
	ID			VARCHAR2(10),	-- 제품 ID
	NAME		NVARCHAR2(30),	-- 제품 명
	PRICE		NUMBER(10, 0),	-- 가격
	POINT		NUMBER(1, 0)	DEFAULT 0, -- 적립 포인트
	DIV			NUMBER(1, 0)	DEFAULT 1, -- 구분 1 : 커피, 3 : 무카페인, 4 : 쥬스
	CONTENT		CLOB,			-- 제품 설명
	INDATE		DATE,			-- 생성일
	OUTDATE		DATE,			-- 종료일
	STATUS		NUMBER(1, 0)	DEFAULT 0,	-- 0 : 정상판매, 1 : 판매금지
	CONSTRAINT	PK_PRODUCT	PRIMARY KEY (ID)
);

-- 제품 이미지
CREATE TABLE PRODUCT_IMG(
	PRODUCT_ID	VARCHAR2(10),	-- 제품 ID
	ID			VARCHAR2(10),	-- 이미지 ID
	DIV			NUMBER(1, 0)	DEFAULT 0, -- 구분 0 : 일반이미지, 1 : 메인이미지
	FILENAME	NVARCHAR2(200),	-- 파일경로
	BFILE		BLOB,			-- 이미지
	INDATE		DATE,			-- 생성일
	OUTDATE		DATE,			-- 종료일
	STATUS		NUMBER(1, 0)	DEFAULT 0,	-- 0 : 정상, 1 : 미사용
	CONSTRAINT	PK_PRODUCT_IMG	PRIMARY KEY (ID),
	CONSTRAINT	FK_PRODUCT_IMG_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (ID)
);

-- 가맹점
CREATE TABLE SUB_COM(
	COM_ID		VARCHAR2(10),	-- 회사 ID
	ID			VARCHAR2(10),	-- 가맹점 ID
	NAME		NVARCHAR2(30),	-- 가맹점 명
	TEL			VARCHAR2(20),	-- 대표전화
	FAX			VARCHAR2(20),	-- FAX
	ADDR		NVARCHAR2(150),	-- 주소
	EMAIL		VARCHAR2(30),	-- 대표 이메일
	INDATE		DATE,			-- 창립일
	OUTDATE		DATE,			-- 폐업일
	STATUS		NUMBER(1, 0)	DEFAULT 0,	-- 0 : 정상운영, 1 : 폐업상태
	CONSTRAINT	PK_SUB_COM	PRIMARY KEY (ID),
	CONSTRAINT	FK_SUB_COM_COMPANY	FOREIGN KEY (COM_ID) REFERENCES COMPANY (ID)
);

-- 고객 
CREATE TABLE CUSTOMER(
	ID			VARCHAR2(30),	-- 고객 ID
	PWD			VARCHAR2(100),	-- PASSWORD
	NAME		NVARCHAR2(30),	-- 이름
	TEL			VARCHAR2(20),	-- 전화
	POINT		NUMBER(2, 0),	-- 적립된 포인트 개수
	CUPON		NUMBER(2, 0),	-- 적립된 쿠폰 개수
	INDATE		DATE			DEFAULT SYSDATE,	-- 가입일
	OUTDATE		DATE,								-- 탈퇴일
	STATUS		NUMBER(1, 0)	DEFAULT 0,			-- 0 : 정상, 1 : 탈퇴
	CONSTRAINT	PK_CUSTOMER PRIMARY KEY (ID)
);

-- 포인트 => 쿠폰 변환 방식
CREATE TABLE CUPON(
	ID			VARCHAR2(10),	-- 쿠폰 ID
	NAME		NVARCHAR2(30),	-- 쿠폰 명
	POINT		NUMBER(2, 0)	DEFAULT 10,	-- 쿠폰 전환 포인트 개수(EX : 포인트 10개 적립 시 쿠폰 1장 발급 시 10 입력)
	INDATE		DATE,			-- 생성일
	OUTDATE		DATE,			-- 종료일
	STATUS		NUMBER(1, 0)	DEFAULT 0,	-- 0 : 정상 운영, 1 : 적용 금지
	CONSTRAINT	PK_CUPON PRIMARY KEY (ID)
);

CREATE TABLE MY_ORDER(
	ID			VARCHAR2(16),				-- 주문 ID
	CUSTOMER_ID	VARCHAR2(30),				-- 고객 ID
	TOT_PRICE	NUMBER(6, 0),				-- 총 금액
	PAY_DIV		NUMBER(1, 0),				-- 결제 구분 1 : 카드결제, 2 : 현금결제, 4 : 쿠폰사용
	CUPON		NUMBER(1, 0),				-- 사용한 쿠폰 개수
	CARD		NUMBER(6, 0),				-- 결제한 금액
	CASH		NUMBER(6, 0),				-- 결제한 금액
	INDATE		DATE			DEFAULT SYSDATE,	-- 주문 날짜시간
	OUTDATE		DATE,						-- 수령 날짜시간
	STATUS		NUMBER(1, 0),	DEFAULT 0,	-- 0 : 주문 및 결제완료, 1 : 수령완료
	CONSTRAINT	PK_MY_ORDER	PRIMARY KEY (ID),
	CONSTRAINT	FK_MY_ORDER_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER (ID),
	CONSTRAINT	FK_MY_ORDER_PRODUCT	FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (ID)
);

CREATE TABLE ORDER_DETAIL(
	ORDER_ID	VARCHAR2(16),				-- 주문 ID
	PRODUCT_ID	VARCHAR2(10),				-- 제품 ID
	CNT			NUMBER(2, 0)	DEFAULT 1,	-- 제품 개수
	TOT_PRICE	NUMBER(6, 0),				-- 가격
	CONSTRAINT	PK_ORDER_DETAIL	PRIMARY KEY (ORDER_ID, PRODUCT_ID),
	CONSTRAINT	FK_ORDER_DETAIL_MY_ORDER FOREIGN KEY (ORDER_ID) REFERENCES MY_ORDER (ID),
	CONSTRAINT	FK_ORDER_DETAIL_PRODUCT	FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (ID)
);
